export const API = 'API';
export const SET_USER_INFO = 'SET_USER_INFO';
export const RESET_USER_INFO = 'RESET_USER_INFO';
export const LOADER = 'LOADER';

export const CREATE_TODO = 'CREATE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const FETCH_ALL_TODO = 'FETCH_ALL_TODO';

export const CREATE_SUB_TODO = 'CREATE_SUB_TODO';
export const FETCH_ALL_SUB_TODO = 'FETCH_ALL_SUB_TODO';
export const UPDATE_SUB_TODO = 'UPDATE_SUB_TODO';
export const UPDATE_CHECK_SUB_TODO = 'UPDATE_CHECK_SUB_TODO';
export const DELETE_SUB_TODO = 'DELETE_SUB_TODO';

export const CREATE_DAILY_TODO = 'CREATE_DAILY_TODO';
export const FETCH_ALL_DAILY_TODO = 'FETCH_ALL_DAILY_TODO';
export const CHECK_DAILY_TODO = 'CHECK_DAILY_TODO';
export const UNCHECK_DAILY_TODO = 'UNCHECK_DAILY_TODO';
export const DELETE_DAILY_TODO = 'DELETE_DAILY_TODO';

export const FETCH_ALL_DAILY_TODO_HISTORY = 'FETCH_ALL_DAILY_TODO_HISTORY';
export const DELETE_DAILY_HISTORY = 'DELETE_DAILY_HISTORY';
